# KKBox Dataset Preprocessing

In [1]:
# Load Python libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

Importing KKBox data

In [2]:
df_train = pd.read_csv('C:/Users/ekwaning/Documents/Flatiron/Capstone/Music-Recommendation/Data/train.csv')
df_train

,msno,song_id,source_system_tab,source_screen_name,source_type,target
0,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik=,explore,Explore,online-playlist,1
1,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,bhp/MpSNoqoxOIB+/l8WPqu6jldth4DIpCm3ayXnJqM=,my library,Local playlist more,local-playlist,1
2,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,JNWfrrC7zNN7BdMpsISKa4Mw+xVJYNnxXh3/Epw7QgY=,my library,Local playlist more,local-playlist,1
3,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,2A87tzfnJTSWqD7gIZHisolhe4DMdzkbd6LzO1KHjNs=,my library,Local playlist more,local-playlist,1
4,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,3qm6XTZ6MOCU11x8FIVbAGH5l5uMkT3/ZalWG1oo2Gc=,explore,Explore,online-playlist,1
...,...,...,...,...,...,...
7377413,6xdFzPlrasIDD95mQWXVC3Bg4ptnGYtBl4ztVEZMddU=,VJTxizih/o28kXCbtPbIyWXScoXGvxyYtl6R+0YB5JM=,my library,Local playlist more,local-playlist,1
7377414,ZxbVmt3Kh/XOH+h58c2Kdj6SjFZk+wnUO006IgWzMQE=,z1mqaU9YOX7T/PFDvUoWozdFq7rC3KwaQP7nFVprjMI=,search,Search,song,0
7377415,ZxbVmt3Kh/XOH+h58c2Kdj6SjFZk+wnUO006IgWzMQE=,750RprmFfLV0bymtDH88g24pLZGVi5VpBAI300P6UOA=,search,Search,song,1
7377416,0aH4Hd3ziPSRHClRX8rkeOEaAG5EPPkW1mKGCdXEok0=,G8wgqObgeAMER/rVCIlgcNeQ8mm0CzF/GsxiMK8TTnA=,discover,Discover Genre,online-playlist,1
7377417,0aH4Hd3ziPSRHClRX8rkeOEaAG5EPPkW1mKGCdXEok0=,Ju0VGkjWeBUZCd7r5Az2hUImhMoWxWLUicOedsmvG0g=,discover,Discover Genre,online-playlist,1

In [3]:
df_train = df_train.sample(frac=0.01)
df_train

,msno,song_id,source_system_tab,source_screen_name,source_type,target
4873923,Ly+hUu353rti8MJ/V8UPgOruHdon7AXRq37RufUFNf4=,qJhZwgQ6cFeHMaA1wO1garktDQOMOFffUcovJm2Nb3M=,search,Album more,album,0
4543452,4u2bShY1j9KZVxiC6XqJ4RYPjAv1kKuYVxvf4LLCaoA=,c2bp6xlq7o3Pj6x95ddX67S/wGsP6qPN/8PqM1DL0a8=,discover,Online playlist more,online-playlist,1
3345688,l1gUeahDY6Y7HfOKe3ACAgFaMUkMec5MdZDw8rB23K0=,vILy7KQyFxIPbaIm5J2mCTEHvMr3/7H7Hl9trGrL+7c=,my library,Local playlist more,local-playlist,1
5726375,0Gl/h+y2oe2/PeMP6rgyulXuTjytK6Qk0elOnTFcDYU=,OH/n6ntOH0M5KeMvwvw9OKpOimbBCriQLo/KhifNKAs=,radio,Radio,radio,0
2311987,TIDqUPHrtFFwhMJYed08ibj+XhKZzXOuOscEMYTQhSA=,IkDJtBpDyGNDx8TF5ua5JQu149j5eld0CkWxZWAkWqw=,my library,Local playlist more,local-library,1
...,...,...,...,...,...,...
7179740,03s2z7tu2Tig2ONcz4JZtVfrjiY6p5jNSqGzhgmAwFw=,w9V7A5WIFl+tKsksMf+iM/1DwHAX77bgyC7NUl1vvpM=,discover,NaN,song,0
2801878,8sEEszoN7JW047C9Qt5XN29r7UJwsb5J6RWTz8gLlqE=,etnpvFVFCKje9Br8nB2pWWlaMRVwN6euSQc9+7ZnXR4=,my library,Local playlist more,local-playlist,1
2974197,Fo3gT4fsSh9BBBSKsl6fafwLtXChadoFvpHwkwba2/M=,ETvg8MFaEMzBfOe1bjD+m7J2EAyXDgG2WQCFXy0OM1U=,search,Online playlist more,online-playlist,1
25496,IpCy1u1+A56JHB2FGSLHAP0l4VG9wk2wIhHHNCm6BvQ=,Kvf/faoTTEtGIuRw+e1fvn70j/T0i1w+Ie/Kfv/e2Vo=,my library,Local playlist more,local-library,1
4142396,Yh/MpoSEPfAmbPY9aH9W6rYM9m1ZGdR8GRWJQUzJFWA=,izWkEacMHX6lc+hEC3QnWwWd2LXiHZ9tacUNpfUz+aw=,listen with,Others profile more,listen-with,0

In [4]:
df_songs = pd.read_csv('C:/Users/ekwaning/Documents/Flatiron/Capstone/Music-Recommendation/Data/songs.csv')
df_songs.head(10)

,song_id,song_length,genre_ids,artist_name,composer,lyricist,language
0,CXoTN1eb7AI+DntdU1vbcwGRV4SCIDxZu+YD8JP8r4E=,247640,465,張信哲 (Jeff Chang),董貞,何啟弘,3.0
1,o0kFgae9QtnYgRkVPqLJwa05zIhRlUjfF7O1tDw0ZDU=,197328,444,BLACKPINK,TEDDY| FUTURE BOUNCE| Bekuh BOOM,TEDDY,31.0
2,DwVvVurfpuz+XPuFvucclVQEyPqcpUkHR0ne1RQzPs0=,231781,465,SUPER JUNIOR,NaN,NaN,31.0
3,dKMBWoZyScdxSkihKG+Vf47nc18N9q4m58+b4e7dSSE=,273554,465,S.H.E,湯小康,徐世珍,3.0
4,W3bqWd3T+VeHFzHAUfARgW9AvVRaF4N5Yzm4Mr6Eo/o=,140329,726,貴族精選,Traditional,Traditional,52.0
5,kKJ2JNU5h8rphyW21ovC+RZU+yEHPM+3w85J37p7vEQ=,235520,864|857|850|843,貴族精選,Joe Hisaishi,Hayao Miyazaki,17.0
6,N9vbanw7BSMoUgdfJlgX1aZPE1XZg8OS1wf88AQEcMc=,226220,458,伍佰 & China Blue,Jonathan Lee,NaN,3.0
7,GsCpr618xfveHYJdo+E5SybrpR906tsjLMeKyrCNw8s=,276793,465,光良 (Michael Wong),光良,彭資閔,3.0
8,oTi7oINPX+rxoGp+3O6llSltQTl80jDqHoULfRoLcG4=,228623,465,林俊傑 (JJ Lin),JJ Lin,Wu Qing Feng,3.0
9,btcG03OHY3GNKWccPP0auvtSbhxog/kllIIOx5grE/k=,232629,352|1995,Kodaline,Stephen Garrigan| Mark Prendergast| Vincent Ma...,Stephen Garrigan| Mark Prendergast| Vincent Ma...,52.0

In [5]:
df_members = pd.read_csv('C:/Users/ekwaning/Documents/Flatiron/Capstone/Music-Recommendation/Data/members.csv')
df_members.head(10)

,msno,city,bd,gender,registered_via,registration_init_time,expiration_date
0,XQxgAYj3klVKjR3oxPPXYYFp4soD4TuBghkhMTD4oTw=,1,0,NaN,7,20110820,20170920
1,UizsfmJb9mV54qE9hCYyU07Va97c0lCRLEQX3ae+ztM=,1,0,NaN,7,20150628,20170622
2,D8nEhsIOBSoE6VthTaqDX8U6lqjJ7dLdr72mOyLya2A=,1,0,NaN,4,20160411,20170712
3,mCuD+tZ1hERA/o5GPqk38e041J8ZsBaLcu7nGoIIvhI=,1,0,NaN,9,20150906,20150907
4,q4HRBfVSssAFS9iRfxWrohxuk9kCYMKjHOEagUMV6rQ=,1,0,NaN,4,20170126,20170613
5,zgPOEyUn5a/Fvuzb3m69ajzxjkbblVtObglW89FzLdo=,13,43,female,9,20120703,20171006
6,Sw9AT8QoR4wWiNUqHZUH6g5ahzGUx4lo1g+Y3xE2f2M=,1,0,NaN,4,20160326,20160329
7,pg6bT2XZkSP1TDBy4qn3HBPY/HffKQ/bg8WIISQYBSY=,1,0,NaN,7,20160130,20170930
8,kfk1AdTNH2dNqF5LzIs4e0vwGPejw2jrnFjJlcYnEgk=,1,0,NaN,7,20110111,20170930
9,tscijwx4dbEp0NXGl+iFtHJ8zrj+TkcMrduOQk9t+gE=,1,0,NaN,7,20160217,20170613

Merging Data sets

In [6]:
#leftjoin songs data to main
df_train = pd.merge(df_train, df_songs, on='song_id', how='left')
df_train.head(10)

,msno,song_id,source_system_tab,source_screen_name,source_type,target,song_length,genre_ids,artist_name,composer,lyricist,language
0,Ly+hUu353rti8MJ/V8UPgOruHdon7AXRq37RufUFNf4=,qJhZwgQ6cFeHMaA1wO1garktDQOMOFffUcovJm2Nb3M=,search,Album more,album,0,71981,451,陳慧琳 (Kelly Chen),Mark Lui,NaN,24.0
1,4u2bShY1j9KZVxiC6XqJ4RYPjAv1kKuYVxvf4LLCaoA=,c2bp6xlq7o3Pj6x95ddX67S/wGsP6qPN/8PqM1DL0a8=,discover,Online playlist more,online-playlist,1,237165,458,Eric 周興哲,Eric Chou,Eric Chou| Xue-Sheng Chen,3.0
2,l1gUeahDY6Y7HfOKe3ACAgFaMUkMec5MdZDw8rB23K0=,vILy7KQyFxIPbaIm5J2mCTEHvMr3/7H7Hl9trGrL+7c=,my library,Local playlist more,local-playlist,1,243356,465,李聖傑 (Sam Lee),NaN,NaN,3.0
3,0Gl/h+y2oe2/PeMP6rgyulXuTjytK6Qk0elOnTFcDYU=,OH/n6ntOH0M5KeMvwvw9OKpOimbBCriQLo/KhifNKAs=,radio,Radio,radio,0,254212,458,張敬軒 (Hins Cheung),Hins Cheung,NaN,24.0
4,TIDqUPHrtFFwhMJYed08ibj+XhKZzXOuOscEMYTQhSA=,IkDJtBpDyGNDx8TF5ua5JQu149j5eld0CkWxZWAkWqw=,my library,Local playlist more,local-library,1,265914,458,游鴻明+彭佳慧,Guo-Hua Chen,An-Xiu Li,3.0
5,YkSiELjVoRNykIbqHfckgo4PG81exSQnEVf/b8EgllQ=,sTTHnqKJzjNPl0jNYylPG2NN3PzN+Y685m9qteLmfH4=,explore,Online playlist more,online-playlist,0,213623,2022,John Lennon,John Lennon| Yoko Ono,NaN,52.0
6,fqisY7ZsIGJsn9sZWUi179xwp5Cb7iRGRWZTSJcO1LI=,eoduKUp/BxirdQJ3pd9yIg3AZuN7ZUdaHtyT1304DVY=,my library,Local playlist more,local-playlist,1,278360,458,楊丞琳 (Rainie Yang),Jia Wang,NaN,3.0
7,qEc1Fi4NwEc2OjeMhOViyATrYQaQV5eCxUkK72c9OqQ=,TbrfWJpl81E4alsi2+b84oeUu+b5S/8n9yFlZDriNYs=,discover,Discover Chart,online-playlist,0,310311,458,楊丞琳 (Rainie Yang),Rong Hao Li,NaN,3.0
8,/2A361q3cuoEFZ0FoMEWj8SIVRJyPpHZQ5ni6Oud88M=,PPkaap1yI5lC442nchdsFERmE/898tGYrA+Uw4E9pmM=,search,Artist more,top-hits-for-artist,1,121103,726,唱唱跳跳學兒歌系列,NaN,陝西民謠,-1.0
9,KXG0wobBnTduE3Q8c6UrX4Yt0VAb51S7+wg2MUAV4Mo=,ZcKgNis1AP1LA0sdtIddrtk7P04iiJzJrXvwXdT/X3Q=,my library,Local playlist more,local-library,1,234161,458,那對夫妻 (Nico&Kim),黃宇哲,林京燁,3.0

In [7]:
#leftjoin members data to main
df_train = pd.merge(df_train, df_members, on='msno', how='left')
df_train.head(10)

,msno,song_id,source_system_tab,source_screen_name,source_type,target,song_length,genre_ids,artist_name,composer,lyricist,language,city,bd,gender,registered_via,registration_init_time,expiration_date
0,Ly+hUu353rti8MJ/V8UPgOruHdon7AXRq37RufUFNf4=,qJhZwgQ6cFeHMaA1wO1garktDQOMOFffUcovJm2Nb3M=,search,Album more,album,0,71981,451,陳慧琳 (Kelly Chen),Mark Lui,NaN,24.0,15,24,male,9,20121125,20170915
1,4u2bShY1j9KZVxiC6XqJ4RYPjAv1kKuYVxvf4LLCaoA=,c2bp6xlq7o3Pj6x95ddX67S/wGsP6qPN/8PqM1DL0a8=,discover,Online playlist more,online-playlist,1,237165,458,Eric 周興哲,Eric Chou,Eric Chou| Xue-Sheng Chen,3.0,1,0,NaN,7,20150807,20171007
2,l1gUeahDY6Y7HfOKe3ACAgFaMUkMec5MdZDw8rB23K0=,vILy7KQyFxIPbaIm5J2mCTEHvMr3/7H7Hl9trGrL+7c=,my library,Local playlist more,local-playlist,1,243356,465,李聖傑 (Sam Lee),NaN,NaN,3.0,8,20,male,9,20121220,20171004
3,0Gl/h+y2oe2/PeMP6rgyulXuTjytK6Qk0elOnTFcDYU=,OH/n6ntOH0M5KeMvwvw9OKpOimbBCriQLo/KhifNKAs=,radio,Radio,radio,0,254212,458,張敬軒 (Hins Cheung),Hins Cheung,NaN,24.0,5,28,female,9,20071027,20170609
4,TIDqUPHrtFFwhMJYed08ibj+XhKZzXOuOscEMYTQhSA=,IkDJtBpDyGNDx8TF5ua5JQu149j5eld0CkWxZWAkWqw=,my library,Local playlist more,local-library,1,265914,458,游鴻明+彭佳慧,Guo-Hua Chen,An-Xiu Li,3.0,1,0,NaN,7,20131029,20170924
5,YkSiELjVoRNykIbqHfckgo4PG81exSQnEVf/b8EgllQ=,sTTHnqKJzjNPl0jNYylPG2NN3PzN+Y685m9qteLmfH4=,explore,Online playlist more,online-playlist,0,213623,2022,John Lennon,John Lennon| Yoko Ono,NaN,52.0,9,26,male,7,20140626,20170930
6,fqisY7ZsIGJsn9sZWUi179xwp5Cb7iRGRWZTSJcO1LI=,eoduKUp/BxirdQJ3pd9yIg3AZuN7ZUdaHtyT1304DVY=,my library,Local playlist more,local-playlist,1,278360,458,楊丞琳 (Rainie Yang),Jia Wang,NaN,3.0,22,26,male,9,20071020,20171030
7,qEc1Fi4NwEc2OjeMhOViyATrYQaQV5eCxUkK72c9OqQ=,TbrfWJpl81E4alsi2+b84oeUu+b5S/8n9yFlZDriNYs=,discover,Discover Chart,online-playlist,0,310311,458,楊丞琳 (Rainie Yang),Rong Hao Li,NaN,3.0,1,0,NaN,7,20100405,20170926
8,/2A361q3cuoEFZ0FoMEWj8SIVRJyPpHZQ5ni6Oud88M=,PPkaap1yI5lC442nchdsFERmE/898tGYrA+Uw4E9pmM=,search,Artist more,top-hits-for-artist,1,121103,726,唱唱跳跳學兒歌系列,NaN,陝西民謠,-1.0,1,0,NaN,7,20141107,20171003
9,KXG0wobBnTduE3Q8c6UrX4Yt0VAb51S7+wg2MUAV4Mo=,ZcKgNis1AP1LA0sdtIddrtk7P04iiJzJrXvwXdT/X3Q=,my library,Local playlist more,local-library,1,234161,458,那對夫妻 (Nico&Kim),黃宇哲,林京燁,3.0,1,0,NaN,7,20110818,20170917

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73774 entries, 0 to 73773
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   msno                    73774 non-null  object
 1   song_id                 73774 non-null  object
 2   source_system_tab       73534 non-null  object
 3   source_screen_name      69583 non-null  object
 4   source_type             73579 non-null  object
 5   target                  73774 non-null  int64
 6   song_length             73774 non-null  int64
 7   genre_ids               72596 non-null  object
 8   artist_name             73774 non-null  object
 9   composer                56861 non-null  object
 10  lyricist                41879 non-null  object
 11  language                73774 non-null  float64
 12  city                    73774 non-null  int64
 13  bd                      73774 non-null  int64
 14  gender                  44021 non-null  object
 15  registered_via          73774 non-null  int64
 16  registration_init_time  73774 non-null  int64
 17  expiration_date         73774 non-null  int64
dtypes: float64(1), int64(7), object(10)
memory usage: 10.7+ MB

Missing Data values

In [9]:
# Count Na in %
df_train.isnull().sum()/df_train.isnull().count()*100

msno                       0.000000
song_id                    0.000000
source_system_tab          0.325318
source_screen_name         5.680863
source_type                0.264321
target                     0.000000
song_length                0.000000
genre_ids                  1.596769
artist_name                0.000000
composer                  22.925421
lyricist                  43.233388
language                   0.000000
city                       0.000000
bd                         0.000000
gender                    40.329927
registered_via             0.000000
registration_init_time     0.000000
expiration_date            0.000000
dtype: float64

In [10]:
# Replace NA
for i in df_train.select_dtypes(include=['object']).columns:
    df_train[i][df_train[i].isnull()] = 'unknown'
df_train = df_train.fillna(value=0)

In [11]:
# Count Na in %
df_train.isnull().sum()/df_train.isnull().count()*100

msno                      0.0
song_id                   0.0
source_system_tab         0.0
source_screen_name        0.0
source_type               0.0
target                    0.0
song_length               0.0
genre_ids                 0.0
artist_name               0.0
composer                  0.0
lyricist                  0.0
language                  0.0
city                      0.0
bd                        0.0
gender                    0.0
registered_via            0.0
registration_init_time    0.0
expiration_date           0.0
dtype: float64

Format Dates

In [12]:
# Create Dates

# registration_init_time
df_train.registration_init_time = pd.to_datetime(df_train.registration_init_time, format='%Y%m%d', errors='ignore')
df_train['registration_init_time_year'] = df_train['registration_init_time'].dt.year
df_train['registration_init_time_month'] = df_train['registration_init_time'].dt.month
df_train['registration_init_time_day'] = df_train['registration_init_time'].dt.day

# expiration_date
df_train.expiration_date = pd.to_datetime(df_train.expiration_date,  format='%Y%m%d', errors='ignore')
df_train['expiration_date_year'] = df_train['expiration_date'].dt.year
df_train['expiration_date_month'] = df_train['expiration_date'].dt.month
df_train['expiration_date_day'] = df_train['expiration_date'].dt.day

In [13]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73774 entries, 0 to 73773
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   msno                          73774 non-null  object
 1   song_id                       73774 non-null  object
 2   source_system_tab             73774 non-null  object
 3   source_screen_name            73774 non-null  object
 4   source_type                   73774 non-null  object
 5   target                        73774 non-null  int64
 6   song_length                   73774 non-null  int64
 7   genre_ids                     73774 non-null  object
 8   artist_name                   73774 non-null  object
 9   composer                      73774 non-null  object
 10  lyricist                      73774 non-null  object
 11  language                      73774 non-null  float64
 12  city                          73774 non-null  int64
 13  bd                            73774 non-null  int64
 14  gender                        73774 non-null  object
 15  registered_via                73774 non-null  int64
 16  registration_init_time        73774 non-null  datetime64[ns]
 17  expiration_date               73774 non-null  datetime64[ns]
 18  registration_init_time_year   73774 non-null  int64
 19  registration_init_time_month  73774 non-null  int64
 20  registration_init_time_day    73774 non-null  int64
 21  expiration_date_year          73774 non-null  int64
 22  expiration_date_month         73774 non-null  int64
 23  expiration_date_day           73774 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(11), object(10)
memory usage: 14.1+ MB

In [14]:
# Dates to category
df_train['registration_init_time'] = df_train['registration_init_time'].astype('category')
df_train['expiration_date'] = df_train['expiration_date'].astype('category')

In [15]:
# Object data to category
for col in df_train.select_dtypes(include=['object']).columns:
    df_train[col] = df_train[col].astype('category')
    
# Encoding categorical features
for col in df_train.select_dtypes(include=['category']).columns:
    df_train[col] = df_train[col].cat.codes

In [16]:
df_train.head()

,msno,song_id,source_system_tab,source_screen_name,source_type,target,song_length,genre_ids,artist_name,composer,...,gender,registered_via,registration_init_time,expiration_date,registration_init_time_year,registration_init_time_month,registration_init_time_day,expiration_date_year,expiration_date_month,expiration_date_day
0,6903,23334,6,0,0,0,71981,128,6425,4792,...,1,9,2141,547,2012,11,25,2017,9,15
1,1975,17214,0,11,6,1,237165,129,1377,2067,...,2,7,3120,569,2015,8,7,2017,10,7
2,14291,25484,3,8,4,1,243356,132,5573,7634,...,1,9,2165,566,2012,12,20,2017,10,4
3,640,11265,5,13,7,0,254212,129,5325,2730,...,0,9,742,449,2007,10,27,2017,6,9
4,9010,8915,3,8,3,1,265914,129,5780,2555,...,2,7,2476,556,2013,10,29,2017,9,24

In [17]:
df_train.to_csv(r'C:/Users/ekwaning/Documents/Flatiron/Capstone/Music-Recommendation/Data/train_1.csv')